Maybe fix build
[#875](https://github.com/johnny-mnemonic/linux-mainline-autobuilds/actions/runs/27576361728/job/81525625538#step:7:1022)
```
[...]
arch/ia64/kernel/time.c:431:6: error: redefinition of 'update_vsyscall_tz'
  431 | void update_vsyscall_tz(void)
      |      ^~~~~~~~~~~~~~~~~~
In file included from arch/ia64/kernel/time.c:24:
./include/linux/timekeeper_internal.h:203:20: note: previous definition of 'update_vsyscall_tz' with type 'void(void)'
  203 | static inline void update_vsyscall_tz(void)
      |                    ^~~~~~~~~~~~~~~~~~
arch/ia64/kernel/time.c:435:6: error: redefinition of 'update_vsyscall'
  435 | void update_vsyscall(struct timekeeper *tk)
      |      ^~~~~~~~~~~~~~~
./include/linux/timekeeper_internal.h:200:20: note: previous definition of 'update_vsyscall' with type 'void(struct timekeeper *)'
  200 | static inline void update_vsyscall(struct timekeeper *tk)
      |                    ^~~~~~~~~~~~~~~
make[6]: *** [scripts/Makefile.build:289: arch/ia64/kernel/time.o] Error 1
make[5]: *** [scripts/Makefile.build:549: arch/ia64/kernel] Error 2
[...]
```
...with extra patch for now replaying the following upstream commit:
* [9694209](https://github.com/torvalds/linux/commit/96942092d5e67c71af246fa3bc1422cdf80a5dc9)

Considering https://github.com/torvalds/linux/commit/bf8f968a63159661acc20254ccdf0dc3c9f1bac2
I assume ia64 would now need to select `CONFIG_GENERIC_GETTIMEOFDAY`
instead to avoid the empty function defs for update_vsyscall() and
update_vsyscall_tz(). But as it has its own definitions for these and is
not using the generic vdso ones IIUC, that config option is misleading in
that ia64 is actually not using the generic implementations, yet. We'll
see.