Fix build
[#213](https://github.com/johnny-mnemonic/linux-mainline-autobuilds/actions/runs/14081255510/job/39434525312#step:7:3863) failed:
```
drivers/cpufreq/ia64-acpi-cpufreq.c:329:27: error: 'cpufreq_generic_attr' undeclared here (not in a function); did you mean 'cpufreq_generic_get'?
  329 |         .attr           = cpufreq_generic_attr,
      |                           ^~~~~~~~~~~~~~~~~~~~
      |                           cpufreq_generic_get
make[6]: *** [scripts/Makefile.build:207: drivers/cpufreq/ia64-acpi-cpufreq.o] Error 1
```

...due to:

[cpufreq: Remove cpufreq_generic_attrs](https://github.com/torvalds/linux/commit/486729c6012042c486db2a5e4d5dd034fb1d3f3c)