Fix build
[#668](https://github.com/johnny-mnemonic/linux-mainline-autobuilds/actions/runs/21974289643/job/63482352765#step:7:935)
```
[...]
arch/ia64/mm/discontig.c: In function 'paging_init':
arch/ia64/mm/discontig.c:601:9: error: implicit declaration of function 'sparse_init' [-Wimplicit-function-declaration]
  601 |         sparse_init();
      |         ^~~~~~~~~~~
arch/ia64/mm/discontig.c:606:9: error: implicit declaration of function 'free_area_init'; did you mean 'file_ref_init'? [-Wimplicit-function-declaration]
  606 |         free_area_init(max_zone_pfns);
      |         ^~~~~~~~~~~~~~
      |         file_ref_init
make[6]: *** [scripts/Makefile.build:289: arch/ia64/mm/discontig.o] Error 1
make[5]: *** [scripts/Makefile.build:546: arch/ia64/mm] Error 2
[...]
```
...with three patches adapting the ia64 port to the mm changes. Resulting
kernel works on rx2620 and rx2800 i2. A Ski kernel based on this is broken
though and can't successfully execute userspace programs:

```
[    2.037829] This architecture does not have kernel memory protection.
[    2.037829] Run /init as init process
[    2.069161] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000004
[    2.069161] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000004 ]---
```

The reason is still to be found, but the first bad merge is indeed the
[mm one], the three patches are adapting to.

[mm one]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4cff5c05e076d2ee4e34122aa956b84a2eaac587