Fix build
[#217](https://github.com/johnny-mnemonic/linux-mainline-autobuilds/actions/runs/14141477237/job/39623384289#step:7:920) failed:
```
arch/ia64/kernel/msi_ia64.c:16:13: error: static declaration of '__get_cached_msi_msg' follows non-static declaration
   16 | static void __get_cached_msi_msg(struct msi_desc *entry, struct msi_msg *msg)
      |             ^~~~~~~~~~~~~~~~~~~~
In file included from arch/ia64/kernel/msi_ia64.c:8:
./include/linux/msi.h:83:6: note: previous declaration of '__get_cached_msi_msg' with type 'void(struct msi_desc *, struct msi_msg *)'
   83 | void __get_cached_msi_msg(struct msi_desc *entry, struct msi_msg *msg);
      |      ^~~~~~~~~~~~~~~~~~~~
make[6]: *** [scripts/Makefile.build:207: arch/ia64/kernel/msi_ia64.o] Error 1
```

...by dropping this commit, as the upstream merge that required the local definition of __get_cached_msi_msg() was reverted with:

[Revert "Merge tag 'irq-msi-2025-03-23' of git://git.kernel.org/pub/scm/linux/kernel/git/tip/tip"](https://github.com/torvalds/linux/commit/112e43e9fd3b999513b1914e2bf523ae509f4c7d)