Fix build
[#225](https://github.com/johnny-mnemonic/linux-mainline-autobuilds/actions/runs/14222608675/job/39854180634#step:7:831)
```
In file included from ./arch/ia64/include/asm/uaccess.h:41,
                 from ./include/linux/uaccess.h:12,
                 from ./include/linux/sched/task.h:13,
                 from ./include/linux/sched/signal.h:9,
                 from ./include/linux/rcuwait.h:6,
                 from ./include/linux/percpu-rwsem.h:7,
                 from ./include/linux/fs.h:34,
                 from ./include/linux/proc_fs.h:10,
                 from ./include/linux/efi.h:19,
                 from arch/ia64/mm/ioremap.c:9:
./arch/ia64/include/asm/io.h:250:22: error: conflicting types for 'ioremap_prot'; have 'void *(phys_addr_t,  size_t,  long unsigned int)' {aka 'void *(long long unsigned int,  long unsigned int,  long unsigned int)'}
  250 | #define ioremap_prot ioremap_prot
      |                      ^~~~~~~~~~~~
arch/ia64/mm/ioremap.c:32:15: note: in expansion of macro 'ioremap_prot'
   32 | void __iomem *ioremap_prot(phys_addr_t phys_addr, size_t size,
      |               ^~~~~~~~~~~~
./arch/ia64/include/asm/io.h:250:22: note: previous declaration of 'ioremap_prot' with type 'void *(phys_addr_t,  size_t,  pgprot_t)' {aka 'void *(long long unsigned int,  long unsigned int,  pgprot_t)'}
  250 | #define ioremap_prot ioremap_prot
      |                      ^~~~~~~~~~~~
./include/asm-generic/io.h:1113:15: note: in expansion of macro 'ioremap_prot'
 1113 | void __iomem *ioremap_prot(phys_addr_t phys_addr, size_t size,
      |               ^~~~~~~~~~~~
In file included from ./include/linux/linkage.h:7,
                 from ./include/linux/printk.h:8,
                 from ./include/asm-generic/bug.h:22,
                 from ./arch/ia64/include/asm/bug.h:17,
                 from ./include/linux/bug.h:5,
                 from ./include/linux/random.h:6,
                 from ./include/linux/nodemask.h:97,
                 from ./include/linux/numa.h:6,
                 from ./arch/ia64/include/asm/nodedata.h:14,
                 from ./arch/ia64/include/asm/processor.h:81,
                 from ./arch/ia64/include/asm/timex.h:15,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from arch/ia64/mm/ioremap.c:8:
./arch/ia64/include/asm/io.h:250:22: error: conflicting types for 'ioremap_prot'; have 'void *(phys_addr_t,  size_t,  long unsigned int)' {aka 'void *(long long unsigned int,  long unsigned int,  long unsigned int)'}
  250 | #define ioremap_prot ioremap_prot
      |                      ^~~~~~~~~~~~
./include/linux/export.h:70:28: note: in definition of macro '__EXPORT_SYMBOL'
   70 |         extern typeof(sym) sym;                                 \
      |                            ^~~
./include/linux/export.h:83:41: note: in expansion of macro '_EXPORT_SYMBOL'
   83 | #define EXPORT_SYMBOL(sym)              _EXPORT_SYMBOL(sym, "")
      |                                         ^~~~~~~~~~~~~~
arch/ia64/mm/ioremap.c:72:1: note: in expansion of macro 'EXPORT_SYMBOL'
   72 | EXPORT_SYMBOL(ioremap_prot);
      | ^~~~~~~~~~~~~
arch/ia64/mm/ioremap.c:72:15: note: in expansion of macro 'ioremap_prot'
   72 | EXPORT_SYMBOL(ioremap_prot);
      |               ^~~~~~~~~~~~
./arch/ia64/include/asm/io.h:250:22: note: previous declaration of 'ioremap_prot' with type 'void *(phys_addr_t,  size_t,  pgprot_t)' {aka 'void *(long long unsigned int,  long unsigned int,  pgprot_t)'}
  250 | #define ioremap_prot ioremap_prot
      |                      ^~~~~~~~~~~~
./include/asm-generic/io.h:1113:15: note: in expansion of macro 'ioremap_prot'
 1113 | void __iomem *ioremap_prot(phys_addr_t phys_addr, size_t size,
      |               ^~~~~~~~~~~~
make[6]: *** [scripts/Makefile.build:207: arch/ia64/mm/ioremap.o] Error 1
```

...due to:

https://github.com/torvalds/linux/commit/86758b504864913233f6a16076184ba784cd4466

...with extra patch.