Fix build
[#224](https://github.com/johnny-mnemonic/linux-mainline-autobuilds/actions/runs/14218760839/job/39841424064#step:7:868)
```
arch/ia64/mm/init.c: In function 'mem_init':
arch/ia64/mm/init.c:467:9: error: implicit declaration of function 'set_max_mapnr' [-Wimplicit-function-declaration]
  467 |         set_max_mapnr(max_low_pfn);
      |         ^~~~~~~~~~~~~
arch/ia64/mm/init.c:469:9: error: implicit declaration of function 'memblock_free_all'; did you mean 'memblock_free_late'? [-Wimplicit-function-declaration]
  469 |         memblock_free_all();
      |         ^~~~~~~~~~~~~~~~~
      |         memblock_free_late
make[6]: *** [scripts/Makefile.build:207: arch/ia64/mm/init.o] Error 1
```

...due to:

* https://github.com/torvalds/linux/commit/8268af309d07d1c6279080b4e6fd16ec75cc977c
* https://github.com/torvalds/linux/commit/8afa901c147a41f92e83943cddf154bbb7995ee6

...with two extra patches.