Fix build
[run #208](https://github.com/johnny-mnemonic/linux-mainline-autobuilds/actions/runs/14050633016/job/39340219012#step:7:878) failed:
```
arch/ia64/kernel/crash.c: In function 'crash_save_this_cpu':
arch/ia64/kernel/crash.c:59:36: error: 'KEXEC_CORE_NOTE_NAME' undeclared (first use in this function)
   59 |         buf = append_elf_note(buf, KEXEC_CORE_NOTE_NAME, NT_PRSTATUS, prstatus,
      |                                    ^~~~~~~~~~~~~~~~~~~~
arch/ia64/kernel/crash.c:59:36: note: each undeclared identifier is reported only once for each function it appears in
make[6]: *** [scripts/Makefile.build:207: arch/ia64/kernel/crash.o] Error 1
make[5]: *** [scripts/Makefile.build:465: arch/ia64/kernel] Error 2
make[4]: *** [scripts/Makefile.build:465: arch/ia64] Error 2
make[4]: *** Waiting for unfinished jobs....
```

...due to:

[crash: Remove KEXEC_CORE_NOTE_NAME](https://github.com/torvalds/linux/commit/7e620b56d958a5efcb0158c366581e0637fd9a50)

...merged upstream with [4f773fc](https://github.com/torvalds/linux/commit/4f773fcbdb4698175ca908d332a1f7f3d4c8e93c).