Fix build
[#212](https://github.com/johnny-mnemonic/linux-mainline-autobuilds/actions/runs/14074489918/job/39414903144#step:7:888) failed:
```
arch/ia64/kernel/msi_ia64.c: In function 'ia64_set_msi_irq_affinity':
arch/ia64/kernel/msi_ia64.c:27:9: error: implicit declaration of function '__get_cached_msi_msg'; did you mean 'get_cached_msi_msg'? [-Wimplicit-function-declaration]
   27 |         __get_cached_msi_msg(irq_data_get_msi_desc(idata), &msg);
      |         ^~~~~~~~~~~~~~~~~~~~
      |         get_cached_msi_msg
make[6]: *** [scripts/Makefile.build:207: arch/ia64/kernel/msi_ia64.o] Error 1
```

...due to:

[genirq/msi: Make a few functions static](https://github.com/torvalds/linux/commit/537625233537179cb2e8293b2c0dc9c989363f41)