Fix build
[#744](https://github.com/johnny-mnemonic/linux-mainline-autobuilds/actions/runs/24452176374/job/71443535538#step:7:949)
```
[...]
  CC      arch/ia64/kernel/time.o
arch/ia64/kernel/time.c: In function 'update_vsyscall':
arch/ia64/kernel/time.c:443:62: error: 'struct clocksource' has no member named 'archdata'
  443 |         fsyscall_gtod_data.clk_fsys_mmio = tk->tkr_mono.clock->archdata.fsys_mmio;
      |                                                              ^~
make[6]: *** [scripts/Makefile.build:289: arch/ia64/kernel/time.o] Error 1
make[5]: *** [scripts/Makefile.build:548: arch/ia64/kernel] Error 2
make[5]: *** Waiting for unfinished jobs....
  CC      kernel/printk/printk_safe.o
[...]
```

...with extra patch (revert) for now, due to upstream commit [c453b9a](https://github.com/torvalds/linux/commit/c453b9abb4f422461c1493ef74d63af0961a2d30).