Fix build
[#748](https://github.com/johnny-mnemonic/linux-mainline-autobuilds/actions/runs/24502713197/job/71613333285#step:7:884)
```
[...]
In file included from ./arch/ia64/include/asm/uaccess.h:40,
                 from ./include/linux/uaccess.h:13,
                 from ./include/linux/sched/task.h:13,
                 from ./include/linux/sched/signal.h:9,
                 from arch/ia64/kernel/asm-offsets.c:11:
./include/linux/pgtable.h:1998:16: error: conflicting types for 'empty_zero_page'; have 'uint8_t[16384]' {aka 'unsigned char[16384]'}
 1998 | extern uint8_t empty_zero_page[PAGE_SIZE];
      |                ^~~~~~~~~~~~~~~
In file included from ./include/linux/pgtable.h:6:
./arch/ia64/include/asm/pgtable.h:445:22: note: previous declaration of 'empty_zero_page' with type 'long unsigned int[2048]'
  445 | extern unsigned long empty_zero_page[PAGE_SIZE/sizeof(unsigned long)];
      |                      ^~~~~~~~~~~~~~~
./include/linux/pgtable.h:2005:9: warning: "ZERO_PAGE" redefined
 2005 | #define ZERO_PAGE(vaddr) _zero_page(vaddr)
      |         ^~~~~~~~~
./arch/ia64/include/asm/pgtable.h:446:9: note: this is the location of the previous definition
  446 | #define ZERO_PAGE(vaddr)        (virt_to_page(ia64_imva(empty_zero_page)))
      |         ^~~~~~~~~
make[4]: *** [scripts/Makefile.build:184: arch/ia64/kernel/asm-offsets.s] Error 1
make[3]: *** [Makefile:1371: prepare0] Error 2
make[2]: *** [scripts/Makefile.package:165: tar-install] Error 2
make[1]: *** [/home/runner/work/linux-mainline-autobuilds/linux-mainline-autobuilds/linux/Makefile:1754: tar-pkg] Error 2
make: *** [Makefile:248: __sub-make] Error 2
[...]
```

...with one extra patch for now due to the following upstream commits:
* [6215d9f](https://github.com/torvalds/linux/commit/6215d9f4470fbb48245ffdfade821685e2728c65)
* [2651378](https://github.com/torvalds/linux/commit/26513781d1b3a1e8b4b576ed62751d604a69b374)

Also add another patch due to [3a6455d](https://github.com/torvalds/linux/commit/3a6455d56bd7c4cfb1ea35ddae052943065e338e)